import os, time
os.environ["CUDA_VISIBLE_DEVICES"]="-1" 
import pprint
import codecs
import array
import collections
import io
try:
    # Python 2 compat
    import cPickle as pickle
except ImportError:
    import pickle
import tensorflow as tf
from hlstm import TextLSTM

def load_stanford(filename):
    """
    Load model from the output files generated by
    the C code from http://nlp.stanford.edu/projects/glove/.
    The entries of the word dictionary will be of type
    unicode in Python 2 and str in Python 3.
    """

    dct = {}
    vectors = array.array('d')

    # Read in the data.
    with codecs.open(filename, 'r', encoding='ISO-8859-1') as savefile:
        for i, line in enumerate(savefile):
            tokens = line.split(' ')

            word = tokens[0]
            entries = tokens[1:]

            dct[word] = i
            vectors.extend(float(x) for x in entries)
            # Infer word vectors dimensions.

        no_components = len(entries)
        no_vectors = len(dct)
        print "Corpus stats: ", no_components, no_vectors

        # Make these into numpy arrays
        word_vecs = np.array(vectors).reshape(no_vectors, no_components)
        print word_vecs.shape
        print word_vecs[:5]
        inverse_dictionary = {v: k for k, v in dct.items()}
        return (word_vecs, dct, inverse_dictionary)

def main():
    filename = "../glove.6B/glove.6B.200d.txt"
    load_stanford(filename)

if __name__ == "__main__":
    main()